apiVersion: v1
kind: Service
metadata:
  name: {{ template "trino.fullname" . }}
  labels:
    app: {{ template "trino.name" . }}
    chart: {{ template "trino.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.jmx.enabled }}
    - port: {{ .Values.jmx.registryPort }}
      targetPort: jmx-registry
      protocol: TCP
      name: jmx-registry
    - port: {{ .Values.jmx.serverPort }}
      targetPort: jmx-server
      protocol: TCP
      name: jmx-server
    {{- end }}
    {{- range $key, $value := .Values.coordinator.additionalExposedPorts }}
    - port: {{ $value.servicePort }}
      name: {{ $value.name }}
      targetPort: {{ $value.port }}
      protocol: {{ $value.protocol }}
    {{- end }}
  selector:
    app: {{ template "trino.name" . }}
    release: {{ .Release.Name }}
    component: coordinator
